name: Build and Publish

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build-app:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - uses: pnpm/action-setup@v6
      with:
        version: 11
        run_install: true

    - name: Build App
      run: |
        pnpm build

    - name: Publish to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      env:
        environment: "production"
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy build/ --project-name=teddieu-landing-page
