name: Build and Publish

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  build-app:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - uses: pnpm/action-setup@v4
      with:
        version: 8
        run_install: true

    - name: Build App
      run: |
        pnpm build

    - name: Publish to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      env:
        environment: "staging"
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy build/ --project-name=teddieu-landing-page
