name: Build (PR)

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  build-app:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Bypass pnpm release age cutoff
        if: contains(github.event.pull_request.labels.*.name, 'bypass-pnpm-cutoff')
        run: pnpm config set minimumReleaseAge 0

      - name: Install dependencies
        run: pnpm install

      - name: Build App
        run: pnpm build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4
        env:
          environment: "staging"
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy build/ --project-name=teddieu-landing-page