name: Build (PR)

on:
  pull_request:

jobs:
  build-app:
    permissions:
      contents: read
      
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      with:
        version: 8
        run_install: true

    - name: Build App
      run: |
        pnpm build

    - name: Publish to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      env:
        environment: "staging"
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy build/ --project-name=teddieu-landing-page
